### ISSUE TITLE
Make the code operational / python 3 version / requirements

### ISSUE THREAD

**Issue by AmitMY** [ThiagoCF05/NeuralREG#1]
Hi Thiago,
This is very interesting work, but it is unfortunately very hard (dare I say impossible) to run.

- Can you please include a `requirements.txt` file (command `pipreqs .`) 
- Can you please fix the small python3 incompatibility issues (print, and cPickle)

---

- The reason I say "impossible" is the fact that when I try to do the first step in the README:
```bash
python2.7 preprocessing.py
```

The following lines exist:
```py
sys.path.append('../')
sys.path.append('~/workspace/stanford_corenlp_pywrapper')
```

Which unless running on your machine, probably won't have all dependencies.

**Comment by ThiagoCF05** [comment]
Dear @Amit,

I am very sorry about that. I will fix all the dependencies to run the preprocessing step until May 3rd. Is this deadline reasonable?

**Comment by ThiagoCF05** [comment]
By the way, the folder "data/" contains the files that are generated by the "preprocessing.py" script. In case you want to run all the other scripts of the models whereas I fix the dependencies for the preprocessing one, this is also possible.

**Comment by AmitMY** [comment]
Cool, didn't notice the data in `data` directory! Awesome.
Don't try to do it on my deadlines, I'm just interested in the method, that is all. I was about to fine tune BERT on this task when you quickly replied.

So thanks for the swift reply, running:
```bash
python3 attention.py --dynet-autobatch 1 --dynet-mem 8192
```
Works for me, and the loss seems to be going down :)

Thanks again!

**Comment by ThiagoCF05** [comment]
Dependencies have been provided on `requirements.txt` and `preprocessing.py` was updated. I am closing the issue now.
